import z from 'zod'

export const applicationMatchSchema = z.object({
  body: z.object({
    requestedAmount: z.number().positive({ message: 'requestedAmount must be a positive number.' }),
    borrowerType: z.enum(['consumer', 'business']),
    loanType: z.enum([
      'Student Loan',
      'Equipment Financing Loan',
      'Working Capital Loan',
      'Term Loan',
      'Line Of Credit Loan',
      'Sba Loan'
    ]),
    industry: z.enum(['restaurant', 'travel', 'construction']).optional(),
    state: z.enum([
      'AL',
      'AK',
      'AS',
      'AZ',
      'AR',
      'CA',
      'CO',
      'CT',
      'DE',
      'DC',
      'FL',
      'GA',
      'GU',
      'HI',
      'ID',
      'IL',
      'IN',
      'IA',
      'KS',
      'KY',
      'LA',
      'ME',
      'MD',
      'MA',
      'MI',
      'MN',
      'MS',
      'MO',
      'MT',
      'NE',
      'NV',
      'NH',
      'NJ',
      'NM',
      'NY',
      'NC',
      'ND',
      'MP',
      'OH',
      'OK',
      'OR',
      'PA',
      'PR',
      'RI',
      'SC',
      'SD',
      'TN',
      'TX',
      'UT',
      'VT',
      'VI',
      'VA',
      'WA',
      'WV',
      'WI',
      'WY'
    ]),
    riskLevel: z.number().gte(1).lte(100)
  })
})
